	DROP TABLE ALUMNO CASCADE CONSTRAINT;
		
    CREATE TABLE ALUMNO (
        NIF VARCHAR(9),
        EDAD SMALLINT NOT null,
        NOMBRE VARCHAR(30),
        APELLIDO VARCHAR(30),
        PRIMARY KEY (NIF)
    );
