DROP TABLE FACTURAS CASCADE CONSTRAINTS;

CREATE TABLE FACTURAS(
  NRO     INTEGER PRIMARY KEY,
  CLIENTE VARCHAR(10),
  FECHA   DATE,
  TOTAL   NUMERIC(8,2),
  DIRECCION VARCHAR(100),
  CP VARCHAR(5),
  CIUDAD VARCHAR(20)
  );
  
DROP TABLE LINEASFACTURA;

CREATE TABLE LINEASFACTURA(
  LINEA         INTEGER,
  NRO           INTEGER REFERENCES FACTURAS,
  DESCRIPCION   VARCHAR(10),
  UNIDADES      INTEGER,
  IMPORTE       NUMERIC(7,2),
  PRIMARY KEY (LINEA, NRO));
  
INSERT INTO FACTURAS VALUES ( 1, 'Pepe', DATE '2013-4-3', 15, 'Avda. Francisco Vitoria s/n', '09006', 'Burgos');
INSERT INTO LINEASFACTURA VALUES ( 1, 1, 'Articulo1', 5, 10);
INSERT INTO LINEASFACTURA VALUES ( 2, 1, 'Articulo2', 5, 5);  

INSERT INTO FACTURAS VALUES ( 2, 'Ana', DATE '2013-2-3', 25, 'Carretera Valladolid s/n', '09001', 'Burgos');
INSERT INTO LINEASFACTURA VALUES ( 1, 2, 'Articulo1', 5,  10);
INSERT INTO LINEASFACTURA VALUES ( 2, 2, 'Articulo2', 15, 15);

COMMIT;
EXIT;

